const data = {
  products: [
    {
      _id: '1',
      name: '100% Linen Turkish Towel',
      category: 'Towels',
      image: '/images/p1.jpg',
      price: 120,
      brand: 'SilkRoadHome',
      rating: 4.5,
      numReviews: 32,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: '100% Linen Turkish Hand Towel',
      category: 'Towels',
      image: '/images/p2.jpg',
      price: 90,
      brand: 'SilkRoadHome',
      rating: 4.0,
      numReviews: 22,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: '100% Linen Turkish Pajama Set',
      category: 'Clothing',
      image: '/images/p3.jpg',
      price: 220,
      brand: 'SilkRoadHome',
      rating: 5.0,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: '100% Cotton Turkish Bathrobe',
      category: 'Clothing',
      image: '/images/p4.jpg',
      price: 190,
      brand: 'SilkRoadHome',
      rating: 5.0,
      numReviews: 27,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Turkish Takunya Bath Sandals',
      category: 'Shoes',
      image: '/images/p5.jpg',
      price: 75,
      brand: 'SilkRoadHome',
      rating: 5.0,
      numReviews: 3,
      description: 'high quality product',
    },
  ],
};

export default data;